kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nginx-html-pvc
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
kind: Pod
apiVersion: v1
metadata:
  name: nginx-pod
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    volumeMounts:
      - name: html
        mountPath: "//usr/share/nginx/html"
  volumes:
    - name: html
      persistentVolumeClaim:
        claimName: nginx-html-pvc
