apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-path
  annotations:
    defaultVolumeType: hostPath
provisioner: rancher.io/local-path
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  pathPattern: "${.PVC.namespace}-${.PVC.name}"