kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-controller-pvc
  namespace: jenkins
  labels:
    "app.kubernetes.io/name": "jenkins"
    "app.kubernetes.io/instance": "jenkins"
    "app.kubernetes.io/component": "jenkins-controller"
spec:
  storageClassName: longhorn
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: "5Gi"
---